apiVersion: v1
kind: Service
metadata:
  name: svc04
spec:
  selector:
    app: task04
  ports:
  - name: http1
    protocol: TCP
    port: 9001
    targetPort: 80
  - name: http2
    protocol: TCP
    port: 9002
    targetPort: 8080
#  - name: http3
#    protocol: TCP
#    port: 9003
#    targetPort: 8080
  externalIPs:
    - 192.168.120.100
